### ISSUE TITLE
Unable to import Neocities Library

### ISSUE THREAD

**Issue by KoungMyatHein** [neocities/python-neocities#3]
Python3.6 complains that the Library does not exist when trying to import.

Python file attached.
[spreadsheet.txt](https://github.com/neocities/python-neocities/files/1804215/spreadsheet.txt)

**Comment by KoungMyatHein** [comment]
The code is just for my personal use and is very shoddy. I apologize for the half-baked code. :)

**Comment by soulshake** [comment]
You're running your code with `python3`, and you ran `python setup.py install`, right? If so, the installer probably ran with python 2.

What is the output of `python --version`? If it's `2.x`, you probably need to run `python3 setup.py install`.

**Comment by KoungMyatHein** [comment]
The version is Python 3.6.4

**Comment by KoungMyatHein** [comment]
![screenshot 68](https://user-images.githubusercontent.com/37309366/37305906-02dafc36-2671-11e8-8bf9-90db71772d60.png)
Screenshot shows that Neocities Library is installed.

**Comment by KoungMyatHein** [comment]
Issue solved by updating virtual environment.
